# Generated by Django 5.0.2 on 2024-02-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('number', models.IntegerField()),
                ('message', models.TextField(max_length=100)),
                ('gender', models.CharField(max_length=1)),
            ],
        ),
    ]
