# Generated by Django 5.0.2 on 2024-02-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_contactmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='number',
            field=models.BigIntegerField(),
        ),
    ]
