# Generated by Django 5.0.2 on 2024-02-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_articlemodel_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='topic',
            field=models.CharField(max_length=40),
        ),
    ]
