# Generated by Django 5.0.2 on 2024-03-01 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_articlemodel_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='content',
            field=models.CharField(max_length=300),
        ),
    ]
